# Generated by Django 5.2.12 on 2026-03-14 08:12

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('mobileno', models.CharField(max_length=15, unique=True)),
                ('alternate_mobileno', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=300)),
                ('zipcode', models.IntegerField()),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='customer_images/')),
                ('user_password', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_specs', models.CharField(blank=True, max_length=400, null=True)),
                ('product_type', models.CharField(max_length=50)),
                ('product_price', models.BigIntegerField()),
                ('product_stock', models.BigIntegerField()),
                ('product_status', models.CharField(max_length=20)),
                ('product_description', models.TextField()),
                ('product_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='product_images/')),
                ('product_video', models.FileField(blank=True, null=True, upload_to='product_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('mobileno', models.CharField(max_length=15, unique=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='vendor_images/')),
                ('vendor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_password', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_amount', models.BigIntegerField()),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_type', models.CharField(max_length=30)),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=150, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_address', models.CharField(max_length=400)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.products')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.vendor')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_message', models.CharField(blank=True, max_length=300, null=True)),
                ('feedback_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='feedback_images/')),
                ('feedback_video', models.FileField(blank=True, null=True, upload_to='feedback_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.products')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('search_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('search_data', models.CharField(blank=True, max_length=200, null=True)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
            ],
            options={
                'db_table': 'search',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.vendor'),
        ),
    ]
